name: Chairs
version: 2.0.1
description: Let players sit on blocks.
authors: 
 - spoothie
 - cnaude
main: net.spoothie.chairs.Chairs
commands:
    chairs:
        description: Various commands for Chairs.
        usage: |
          /<command> reload - reloads the configuration
          /<command> off  - disable chairs for self
          /<command> on - enable chairs for self
